### PR TITLE
ACCRE Scholar Ziqi Yang 2016 summer

### PR DESCRIPTION
**Pull request by kenyangzq**
This pull request contains some of the code I wrote in the summer. I believed they are specifically designed for the energy minimizing problem in Math or Physics. 

There are README files in each folder.

Ziqi Yang

### CODE REVIEW

**Comment by frenchwr** [comment]
Thanks @kenyangzq. Could you trim this down to just a handful of essential files? Are you pushing an entire external library or something like that?

**Comment by kenyangzq** [comment]
Hi,

I will work on it this week. Some of the files are examples and outputs. I
will trim down to only the essential part.

Ziqi Yang

**Comment by frenchwr** [comment]
Looking good! A few more requests and then I think this is ready to be merged into the repo:
1. Could you remove the white spaces from the directory name (Conjugate Gradient Descent)?
2. Could you include a SLURM script demonstrating how to run these tools on the ACCRE cluster? This can be very simple toy example.

**Comment by kenyangzq** [comment]
Sure,

I will do it tonight.

Ziqi Yang

2016年8月24日星期三，Will French notifications@github.com 写道：

**Comment by frenchwr** [comment]
Completely forgot to merge these @kenyangzq. Thanks for the contribution!

**Pull request merged**
